import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  statSync,
  utimesSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { runContractCommand } from './contract.js';

const fixture = fileURLToPath(new URL('../__fixtures__/contract/en.json', import.meta.url));

const EXPECTED = `// Generated by Etyma from a source message catalog. Do not edit.
// Regenerate it with \`etyma contract\` (local JSON) or etymaRemoteContract (remote catalog).

import { defineMessageContract } from '@etyma/core';

export default defineMessageContract(
  [
    "footer.rights",
    "nav.docs",
    "onboarding.steps.0",
    "onboarding.steps.1",
    "welcome",
  ] as const,
  {
    "footer.rights": ["year"],
    "onboarding.steps.1": ["plan"],
    "welcome": ["name"],
  } as const,
);
`;

describe('runContractCommand', () => {
  let dir: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'etyma-cli-contract-'));
  });

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  function source(name: string, text: string): string {
    const path = join(dir, name);
    writeFileSync(path, text);
    return path;
  }

  it('writes exact keys, array indexes included, and each message variables', async () => {
    const result = await runContractCommand([fixture, '--output', 'etyma.generated.ts'], dir);

    expect(result).toEqual({
      exitCode: 0,
      stdout: '✓ Wrote etyma.generated.ts (5 keys)\n',
      stderr: '',
    });
    expect(readFileSync(join(dir, 'etyma.generated.ts'), 'utf8')).toBe(EXPECTED);
  });

  it('resolves both paths against cwd and accepts -o', async () => {
    mkdirSync(join(dir, 'src/i18n'), { recursive: true });
    writeFileSync(join(dir, 'src/i18n/en.json'), readFileSync(fixture));

    const result = await runContractCommand(
      ['./src/i18n/en.json', '-o', './src/i18n/etyma.generated.ts'],
      dir,
    );

    expect(result.exitCode).toBe(0);
    expect(readFileSync(join(dir, 'src/i18n/etyma.generated.ts'), 'utf8')).toBe(EXPECTED);
  });

  it('creates missing output directories', async () => {
    const result = await runContractCommand(
      [fixture, '--output', 'src/generated/i18n/contract.ts'],
      dir,
    );

    expect(result.exitCode).toBe(0);
    expect(readFileSync(join(dir, 'src/generated/i18n/contract.ts'), 'utf8')).toBe(EXPECTED);
  });

  it('does not rewrite an output that is already current', async () => {
    const output = join(dir, 'etyma.generated.ts');
    await runContractCommand([fixture, '--output', output], dir);

    const past = new Date('2020-01-01T00:00:00Z');
    utimesSync(output, past, past);

    const result = await runContractCommand([fixture, '--output', output], dir);

    expect(result.exitCode).toBe(0);
    expect(result.stdout).toBe('✓ etyma.generated.ts is up to date (5 keys)\n');
    expect(statSync(output).mtime.getTime()).toBe(past.getTime());
  });

  it('rewrites an output that is stale', async () => {
    const output = join(dir, 'etyma.generated.ts');
    writeFileSync(output, 'stale\n');

    const result = await runContractCommand([fixture, '--output', output], dir);

    expect(result.stdout).toBe('✓ Wrote etyma.generated.ts (5 keys)\n');
    expect(readFileSync(output, 'utf8')).toBe(EXPECTED);
  });

  it('is byte-stable whatever the source key order or formatting', async () => {
    const reordered = source(
      'reordered.json',
      JSON.stringify({
        welcome: 'Hello, {$name}!',
        onboarding: { steps: ['Create an account', 'Choose {$plan}'] },
        footer: { rights: '© {$year :number useGrouping=never}' },
        nav: { docs: 'Docs' },
      }),
    );

    await runContractCommand([reordered, '--output', 'a.ts'], dir);

    expect(readFileSync(join(dir, 'a.ts'), 'utf8')).toBe(EXPECTED);
  });

  it('renders the keys-only module for a catalog with no variables', async () => {
    await runContractCommand([source('en.json', '{"nav":{"docs":"Docs"}}'), '-o', 'c.ts'], dir);

    expect(readFileSync(join(dir, 'c.ts'), 'utf8')).toContain(
      'export default defineMessageContract([\n  "nav.docs",\n] as const);\n',
    );
  });

  describe.each([
    ['malformed JSON', '{"nav": ', /"en\.json" is not valid JSON: /],
    ['an array root', '["a"]', /root is an array/],
    ['a number leaf', '{"count": 3}', /"count" is a number/],
    ['a null leaf', '{"nav": {"docs": null}}', /"nav\.docs" is null/],
    ['a dotted key', '{"nav.docs": "Docs"}', /key "nav\.docs" contains a "\."/],
    ['an empty array', '{"steps": []}', /"steps" is an empty array/],
    ['a mixed array', '{"steps": ["One", 2]}', /"steps\.1" is a number/],
    ['no messages', '{}', /"en\.json" has no messages/],
    [
      'invalid MessageFormat 2',
      '{"ok": "Hi {$who}", "welcome": "Hello, {$name"}',
      /1 source message is not valid MessageFormat 2, so its variables cannot be read:\n {2}welcome: Invalid MessageFormat 2 syntax/,
    ],
  ])('for %s', (_name, text, expected) => {
    it('exits 2 and writes nothing', async () => {
      const result = await runContractCommand([source('en.json', text), '-o', 'out.ts'], dir);

      expect(result.exitCode).toBe(2);
      expect(result.stdout).toBe('');
      expect(result.stderr).toMatch(/^etyma contract: /);
      expect(result.stderr).toMatch(expected);
      expect(() => statSync(join(dir, 'out.ts'))).toThrow();
    });
  });

  it('keeps an existing contract when generation fails', async () => {
    const output = join(dir, 'out.ts');
    writeFileSync(output, 'previous\n');

    const result = await runContractCommand([source('en.json', '{"a": "{$x"}'), '-o', output], dir);

    expect(result.exitCode).toBe(2);
    expect(readFileSync(output, 'utf8')).toBe('previous\n');
  });

  it.each([
    [[], /Missing required argument <source\.json>/],
    [['en.json'], /Missing required option --output <file>/],
    [['a.json', 'b.json', '-o', 'x.ts'], /Too many arguments/],
    [['en.json', '--source', 'en', '-o', 'x.ts'], /Unknown option '--source'/],
    [['en.json', '-o', 'en.json'], /--output must not be the source catalog itself/],
    [['missing.json', '-o', 'x.ts'], /Cannot read "missing\.json": ENOENT/],
  ])('exits 2 for usage and filesystem errors: %j', async (argv, expected) => {
    const result = await runContractCommand(argv, dir);

    expect(result.exitCode).toBe(2);
    expect(result.stderr).toMatch(expected);
  });

  it('prints its help for --help', async () => {
    const result = await runContractCommand(['--help'], dir);

    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain('etyma contract <source.json> --output <file>');
  });
});
