/// <reference types="node" />

import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

// The workspace root's TypeScript - the same compiler `pnpm typecheck` runs this package with.
import ts from 'typescript';
import { afterEach, describe, expect, it } from 'vitest';

import { myBlogEs } from './__fixtures__/my-blog.js';
import { paramSamples } from './__fixtures__/param-samples.js';
import {
  extractContractKeys,
  extractContractParams,
  extractContractVariables,
  renderContractModule,
} from './generate-contract.js';

describe('extractContractVariables', () => {
  it('lists each message’s external variables, read by the MF2 parser, sorted', () => {
    expect(
      extractContractVariables({
        welcome: 'Hello, {$name}!',
        nav: { docs: 'Docs' },
        footer: { rights: '© {$year :number useGrouping=never} {$author}' },
        count:
          '.input {$count :number}\n.match $count\none {{{$count} item}}\n*   {{{$count} items}}',
        total: '.local $sum = {$price :number}\n{{Total: {$sum}}}',
        steps: ['Create an account', 'Choose {$plan}'],
      }),
    ).toEqual({
      count: ['count'],
      'footer.rights': ['author', 'year'],
      'steps.1': ['plan'],
      total: ['price'],
      welcome: ['name'],
    });
  });

  it('matches the real my-blog catalog', () => {
    expect(extractContractVariables(myBlogEs)).toEqual({ 'footer.rights': ['author', 'year'] });
  });

  it('leaves a message that is not valid MessageFormat 2 untyped instead of guessing', () => {
    expect(extractContractVariables({ broken: 'Hello {$name', ok: 'Hi {$who}' })).toEqual({
      ok: ['who'],
    });
  });

  it('with strict, throws naming every message that is not valid MessageFormat 2', () => {
    expect(() =>
      extractContractVariables(
        { z: 'Bye {$name', ok: 'Hi {$who}', a: { b: '{$x' } },
        { strict: true },
      ),
    ).toThrow(
      /^2 source messages are not valid MessageFormat 2, so their variables cannot be read:\n {2}a\.b: Invalid MessageFormat 2 syntax: .+\n {2}z: Invalid MessageFormat 2 syntax: /,
    );
  });

  it('with strict, still reads a message that parses but breaks a data-model rule', () => {
    expect(
      extractContractVariables(
        { pick: '.input {$n :number}\n.match $n\none {{One}}' },
        { strict: true },
      ),
    ).toEqual({ pick: ['n'] });
  });

  it('with strict, returns the same result as without for a valid catalog', () => {
    const source = { welcome: 'Hello, {$name}!', steps: ['A', 'Choose {$plan}'] };

    expect(extractContractVariables(source, { strict: true })).toEqual(
      extractContractVariables(source),
    );
  });

  it('rejects a malformed catalog shape, like extractContractKeys', () => {
    expect(() => extractContractVariables({ steps: [] })).toThrow(/empty array/);
  });
});

describe('extractContractParams', () => {
  const source = {
    welcome: 'Hello, {$name}!',
    total: 'Total: {$count :number}',
    updated: '{$when :datetime}',
    plural: '.input {$n :number}\n{{{$n :datetime}}}',
    format: '{$amount :number minimumFractionDigits=$digits}',
    custom: '{$user :avatar}',
    steps: ['Create an account', 'Pay {$amount :currency currency=EUR}'],
  };

  it('reads variables and the functions each variable reaches, from one parse', () => {
    expect(extractContractParams(source)).toEqual({
      variables: {
        custom: ['user'],
        format: ['amount', 'digits'],
        plural: ['n'],
        'steps.1': ['amount'],
        total: ['count'],
        updated: ['when'],
        welcome: ['name'],
      },
      functions: {
        custom: { user: ['avatar'] },
        format: { amount: ['number'] },
        plural: { n: ['number'] },
        'steps.1': { amount: ['currency'] },
        total: { count: ['number'] },
        updated: { when: ['datetime'] },
      },
    });
  });

  it('agrees with extractContractVariables on variables', () => {
    expect(extractContractParams(source).variables).toEqual(extractContractVariables(source));
  });

  it('guesses nothing for invalid MessageFormat 2, and still throws with strict', () => {
    expect(extractContractParams({ broken: '{$n :number', ok: '{$m :number}' })).toEqual({
      variables: { ok: ['m'] },
      functions: { ok: { m: ['number'] } },
    });
    expect(() => extractContractParams({ broken: '{$n :number' }, { strict: true })).toThrow(
      /^1 source message is not valid MessageFormat 2/,
    );
  });
});

describe('renderContractModule with variables', () => {
  it('renders keys and variables, deterministically sorted, leaving empty lists out', () => {
    expect(
      renderContractModule({
        keys: ['welcome', 'nav.docs'],
        variables: { welcome: ['name'], 'nav.docs': [] },
      }),
    ).toBe(
      [
        '// Generated by Etyma from a source message catalog. Do not edit.',
        '// Regenerate it with `etyma contract` (local JSON) or etymaRemoteContract (remote catalog).',
        '',
        "import { defineMessageContract } from '@etyma/core';",
        '',
        'export default defineMessageContract({',
        '  keys: [',
        '    "nav.docs",',
        '    "welcome",',
        '  ],',
        '  variables: {',
        '    "welcome": ["name"],',
        '  },',
        '});',
        '',
      ].join('\n'),
    );
  });

  it('renders functions, deterministically sorted', () => {
    expect(
      renderContractModule({
        keys: ['welcome', 'total'],
        variables: { welcome: ['name'], total: ['label', 'count'] },
        functions: { total: { label: ['string'], count: ['number', 'integer'] } },
      }),
    ).toBe(
      [
        '// Generated by Etyma from a source message catalog. Do not edit.',
        '// Regenerate it with `etyma contract` (local JSON) or etymaRemoteContract (remote catalog).',
        '',
        "import { defineMessageContract } from '@etyma/core';",
        '',
        'export default defineMessageContract({',
        '  keys: [',
        '    "total",',
        '    "welcome",',
        '  ],',
        '  variables: {',
        '    "total": ["count", "label"],',
        '    "welcome": ["name"],',
        '  },',
        '  functions: {',
        '    "total": { "count": ["integer", "number"], "label": ["string"] },',
        '  },',
        '});',
        '',
      ].join('\n'),
    );
  });

  it('leaves out a field with nothing in it', () => {
    expect(
      renderContractModule({ keys: ['welcome'], variables: { welcome: ['name'] }, functions: {} }),
    ).toBe(renderContractModule({ keys: ['welcome'], variables: { welcome: ['name'] } }));
    expect(renderContractModule({ keys: ['nav.docs'], variables: {} })).toBe(
      renderContractModule({ keys: ['nav.docs'] }),
    );
    expect(
      renderContractModule({ keys: ['a'], variables: { a: ['x'] }, functions: { a: { x: [] } } }),
    ).toBe(renderContractModule({ keys: ['a'], variables: { a: ['x'] } }));
  });

  it('composes with extractContractParams', () => {
    const source = { total: '{$count :number} items' };

    expect(
      renderContractModule({ keys: extractContractKeys(source), ...extractContractParams(source) }),
    ).toContain('functions: {\n    "total": { "count": ["number"] },\n  },');
  });
});

/**
 * The generated module is only useful if `@etyma/core` reads it back as typed params. This
 * compiles a real generated contract with the TypeScript compiler, next to a file that
 * asserts what `t()` must and must not accept for it.
 *
 * Each test runs a whole `ts.createProgram`, and the first one pays the compiler's cold start
 * (loading `lib.*.d.ts` and `@etyma/core`'s types). That regularly exceeds Vitest's 5s default
 * under `pnpm run check`, where turbo runs typecheck, test and build concurrently on one CI
 * runner - which failed the release workflow's quality gates, and with them every publish.
 */
describe('a generated contract, compiled', { timeout: 60_000 }, () => {
  const packageRoot = fileURLToPath(new URL('..', import.meta.url));
  let dir: string | undefined;

  afterEach(() => {
    if (dir !== undefined) rmSync(dir, { recursive: true, force: true });
    dir = undefined;
  });

  it('types t() params for the keys it lists variables for, and only those', () => {
    const source = {
      welcome: 'Hello, {$name}!',
      nav: { docs: 'Docs' },
      footer: { rights: '© {$year :number useGrouping=never} {$author}' },
    };

    // Inside the package, so `@etyma/core` resolves the way it does for a consumer.
    dir = mkdtempSync(join(packageRoot, '.contract-check-'));
    writeFileSync(
      join(dir, 'contract.generated.ts'),
      renderContractModule({
        keys: extractContractKeys(source),
        variables: extractContractVariables(source),
      }),
    );
    writeFileSync(
      join(dir, 'check.ts'),
      [
        "import { createTranslator, defineRemoteI18n, type I18nDefinition, type MessageParamsMap, type Translator } from '@etyma/core';",
        "import contract from './contract.generated.js';",
        '',
        'declare function translatorFor<K extends string, P extends MessageParamsMap>(d: I18nDefinition<K, P>): Translator<K, P>;',
        "const t = translatorFor(defineRemoteI18n({ locales: ['en'], sourceLocale: 'en', contract, loaders: { en: () => ({}) } }));",
        '',
        "t.translate('welcome', { name: 'Ada' });",
        "t.translate('footer.rights', { author: 'Andrii', year: 2026 });",
        "t.translate('nav.docs');",
        '// @ts-expect-error - `welcome` needs `name`.',
        "t.translate('welcome');",
        '// @ts-expect-error - `footer.rights` needs `author` too.',
        "t.translate('footer.rights', { year: 2026 });",
        '// @ts-expect-error - not a key.',
        "t.translate('nav.nope');",
        'void createTranslator;',
        '',
      ].join('\n'),
    );

    const program = ts.createProgram([join(dir, 'check.ts')], {
      strict: true,
      noEmit: true,
      skipLibCheck: true,
      target: ts.ScriptTarget.ES2022,
      module: ts.ModuleKind.NodeNext,
      moduleResolution: ts.ModuleResolutionKind.NodeNext,
      types: [],
    });
    const diagnostics = ts
      .getPreEmitDiagnostics(program)
      .map(diagnostic => ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n'));

    expect(diagnostics).toEqual([]);
  });

  it('types every parity sample exactly as its literal would, arrays included', () => {
    const source: Record<string, string | string[]> = Object.fromEntries(
      paramSamples.map(([message], index) => [`s${index}`, message]),
    );
    source['steps'] = ['Create an account', 'Pay {$amount :number}'];

    const params = extractContractParams(source, { strict: true });

    dir = mkdtempSync(join(packageRoot, '.contract-check-'));
    writeFileSync(
      join(dir, 'contract.generated.ts'),
      renderContractModule({ keys: extractContractKeys(source), ...params }),
    );
    writeFileSync(
      join(dir, 'check.ts'),
      [
        "import { defineMessages, defineRemoteI18n, type I18nDefinition, type MessageParamsMap, type MessageParamsOf, type Translator } from '@etyma/core';",
        "import contract from './contract.generated.js';",
        '',
        'type Equal<A, B> = (<T>() => T extends A ? 1 : 2) extends <T>() => T extends B ? 1 : 2 ? true : false;',
        'type Assert<T extends true> = T;',
        `const literal = defineMessages(${JSON.stringify(source)});`,
        'type Literal = MessageParamsOf<typeof literal>;',
        'type Generated = NonNullable<typeof contract.messageParams>;',
        'export type Same = Assert<Equal<Literal, Generated>>;',
        '',
        'declare function translatorFor<K extends string, P extends MessageParamsMap>(d: I18nDefinition<K, P>): Translator<K, P>;',
        "const t = translatorFor(defineRemoteI18n({ locales: ['en'], sourceLocale: 'en', contract, loaders: { en: () => ({}) } }));",
        "t.translate('steps.1', { amount: 9.99 });",
        '// @ts-expect-error - `steps.1` is :number, and a Date is not a numeric input.',
        "t.translate('steps.1', { amount: new Date() });",
        '',
      ].join('\n'),
    );

    const program = ts.createProgram([join(dir, 'check.ts')], {
      strict: true,
      noEmit: true,
      skipLibCheck: true,
      target: ts.ScriptTarget.ES2022,
      module: ts.ModuleKind.NodeNext,
      moduleResolution: ts.ModuleResolutionKind.NodeNext,
      types: [],
    });
    const diagnostics = ts
      .getPreEmitDiagnostics(program)
      .map(diagnostic => ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n'));

    expect(diagnostics).toEqual([]);
  });
});
