/// <reference types="node" />

import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

// The workspace root's TypeScript - the same compiler `pnpm typecheck` runs this package with.
import ts from 'typescript';
import { afterEach, describe, expect, it } from 'vitest';

import { myBlogEs } from './__fixtures__/my-blog.js';
import {
  extractContractKeys,
  extractContractVariables,
  renderContractModule,
} from './generate-contract.js';

describe('extractContractVariables', () => {
  it('lists each message’s external variables, read by the MF2 parser, sorted', () => {
    expect(
      extractContractVariables({
        welcome: 'Hello, {$name}!',
        nav: { docs: 'Docs' },
        footer: { rights: '© {$year :number useGrouping=never} {$author}' },
        count:
          '.input {$count :number}\n.match $count\none {{{$count} item}}\n*   {{{$count} items}}',
        total: '.local $sum = {$price :number}\n{{Total: {$sum}}}',
        steps: ['Create an account', 'Choose {$plan}'],
      }),
    ).toEqual({
      count: ['count'],
      'footer.rights': ['author', 'year'],
      'steps.1': ['plan'],
      total: ['price'],
      welcome: ['name'],
    });
  });

  it('matches the real my-blog catalog', () => {
    expect(extractContractVariables(myBlogEs)).toEqual({ 'footer.rights': ['author', 'year'] });
  });

  it('leaves a message that is not valid MessageFormat 2 untyped instead of guessing', () => {
    expect(extractContractVariables({ broken: 'Hello {$name', ok: 'Hi {$who}' })).toEqual({
      ok: ['who'],
    });
  });

  it('with strict, throws naming every message that is not valid MessageFormat 2', () => {
    expect(() =>
      extractContractVariables(
        { z: 'Bye {$name', ok: 'Hi {$who}', a: { b: '{$x' } },
        { strict: true },
      ),
    ).toThrow(
      /^2 source messages are not valid MessageFormat 2, so their variables cannot be read:\n {2}a\.b: Invalid MessageFormat 2 syntax: .+\n {2}z: Invalid MessageFormat 2 syntax: /,
    );
  });

  it('with strict, still reads a message that parses but breaks a data-model rule', () => {
    expect(
      extractContractVariables(
        { pick: '.input {$n :number}\n.match $n\none {{One}}' },
        { strict: true },
      ),
    ).toEqual({ pick: ['n'] });
  });

  it('with strict, returns the same result as without for a valid catalog', () => {
    const source = { welcome: 'Hello, {$name}!', steps: ['A', 'Choose {$plan}'] };

    expect(extractContractVariables(source, { strict: true })).toEqual(
      extractContractVariables(source),
    );
  });

  it('rejects a malformed catalog shape, like extractContractKeys', () => {
    expect(() => extractContractVariables({ steps: [] })).toThrow(/empty array/);
  });
});

describe('renderContractModule with variables', () => {
  it('renders keys and variables, deterministically sorted', () => {
    expect(
      renderContractModule(['welcome', 'nav.docs'], { welcome: ['name'], 'nav.docs': [] }),
    ).toBe(
      [
        '// Generated by Etyma from a source message catalog. Do not edit.',
        '// Regenerate it with `etyma contract` (local JSON) or etymaRemoteContract (remote catalog).',
        '',
        "import { defineMessageContract } from '@etyma/core';",
        '',
        'export default defineMessageContract(',
        '  [',
        '    "nav.docs",',
        '    "welcome",',
        '  ] as const,',
        '  {',
        '    "nav.docs": [],',
        '    "welcome": ["name"],',
        '  } as const,',
        ');',
        '',
      ].join('\n'),
    );
  });

  it('renders exactly the keys-only module when there is nothing to type', () => {
    expect(renderContractModule(['nav.docs'], {})).toBe(renderContractModule(['nav.docs']));
  });
});

/**
 * The generated module is only useful if `@etyma/core` reads it back as typed params. This
 * compiles a real generated contract with the TypeScript compiler, next to a file that
 * asserts what `t()` must and must not accept for it.
 */
describe('a generated contract, compiled', () => {
  const packageRoot = fileURLToPath(new URL('..', import.meta.url));
  let dir: string | undefined;

  afterEach(() => {
    if (dir !== undefined) rmSync(dir, { recursive: true, force: true });
    dir = undefined;
  });

  it('types t() params for the keys it lists variables for, and only those', () => {
    const source = {
      welcome: 'Hello, {$name}!',
      nav: { docs: 'Docs' },
      footer: { rights: '© {$year :number useGrouping=never} {$author}' },
    };

    // Inside the package, so `@etyma/core` resolves the way it does for a consumer.
    dir = mkdtempSync(join(packageRoot, '.contract-check-'));
    writeFileSync(
      join(dir, 'contract.generated.ts'),
      renderContractModule(extractContractKeys(source), extractContractVariables(source)),
    );
    writeFileSync(
      join(dir, 'check.ts'),
      [
        "import { createTranslator, defineRemoteI18n, type I18nDefinition, type MessageParamsMap, type Translator } from '@etyma/core';",
        "import contract from './contract.generated.js';",
        '',
        'declare function translatorFor<K extends string, P extends MessageParamsMap>(d: I18nDefinition<K, P>): Translator<K, P>;',
        "const t = translatorFor(defineRemoteI18n({ locales: ['en'], sourceLocale: 'en', contract, loaders: { en: () => ({}) } }));",
        '',
        "t.translate('welcome', { name: 'Ada' });",
        "t.translate('footer.rights', { author: 'Andrii', year: 2026 });",
        "t.translate('nav.docs');",
        '// @ts-expect-error - `welcome` needs `name`.',
        "t.translate('welcome');",
        '// @ts-expect-error - `footer.rights` needs `author` too.',
        "t.translate('footer.rights', { year: 2026 });",
        '// @ts-expect-error - not a key.',
        "t.translate('nav.nope');",
        'void createTranslator;',
        '',
      ].join('\n'),
    );

    const program = ts.createProgram([join(dir, 'check.ts')], {
      strict: true,
      noEmit: true,
      skipLibCheck: true,
      target: ts.ScriptTarget.ES2022,
      module: ts.ModuleKind.NodeNext,
      moduleResolution: ts.ModuleResolutionKind.NodeNext,
      types: [],
    });
    const diagnostics = ts
      .getPreEmitDiagnostics(program)
      .map(diagnostic => ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n'));

    expect(diagnostics).toEqual([]);
  });
});
