import { flattenMessages, type MessageSource } from '@etyma/core';

/**
 * Extracts a message catalog's key contract, deterministically sorted.
 *
 * Built on `@etyma/core`'s own `flattenMessages` rather than a second catalog walker: the
 * same validation a static `source` catalog gets - non-empty, no dotted or duplicate keys,
 * every leaf a string - applies here too, and throws the same way, since a malformed remote
 * catalog is exactly as much a configuration bug as a malformed local one.
 *
 * Only the keys are kept. The message values themselves are never part of a generated
 * contract - the remote catalog stays the one place translation content lives.
 */
export function extractContractKeys(source: MessageSource): readonly string[] {
  return [...flattenMessages(source).keys()].sort();
}

const GENERATED_HEADER = [
  '// Generated by Etyma. Do not edit.',
  '// Derived from a remote message catalog - see the Etyma Vite plugin (etymaRemoteContract).',
].join('\n');

/**
 * Renders a {@link https://www.npmjs.com/package/@etyma/core `defineMessageContract`} module
 * from a sorted key list.
 *
 * Byte-stable for a given `keys`: no timestamp, no random id, no machine-specific path -
 * running this twice against the same catalog produces the same file, so committing the
 * output never causes churn the catalog itself did not cause.
 */
export function renderContractModule(keys: readonly string[]): string {
  const sortedKeys = [...keys].sort();
  const literal = sortedKeys.map(key => `  ${JSON.stringify(key)},`).join('\n');

  return (
    `${GENERATED_HEADER}\n` +
    `\n` +
    `import { defineMessageContract } from '@etyma/core';\n` +
    `\n` +
    `export default defineMessageContract([\n${literal}\n] as const);\n`
  );
}
