import { flattenMessages, type MessageSource } from '@etyma/core';

import { analyzeMessage } from './message-analysis.js';

/**
 * Extracts a message catalog's key contract, deterministically sorted.
 *
 * Built on `@etyma/core`'s own `flattenMessages` rather than a second catalog walker: the
 * same validation a static `source` catalog gets - non-empty, no dotted or duplicate keys,
 * every leaf a string - applies here too, and throws the same way, since a malformed remote
 * catalog is exactly as much a configuration bug as a malformed local one.
 *
 * Only the keys are kept. The message values themselves are never part of a generated
 * contract - the remote catalog stays the one place translation content lives.
 */
export function extractContractKeys(source: MessageSource): readonly string[] {
  return [...flattenMessages(source).keys()].sort();
}

/**
 * Extracts each message's external MessageFormat 2 variables, for a contract that types
 * `t()`'s params as well as its keys.
 *
 * Read with the `messageformat` parser, through the same analysis `validateCatalogs` compares
 * variables with - never a regex. Only messages with at least one variable get an entry, and
 * both keys and names are sorted, so the result is deterministic. A message that is not valid
 * MessageFormat 2 gets no entry, and so keeps untyped params: which variables it takes is
 * unknowable, and reporting the syntax error is `etymaRemoteValidation`'s job, not this one's.
 *
 * Throws on a malformed catalog shape exactly as {@link extractContractKeys} does.
 */
export function extractContractVariables(
  source: MessageSource,
): Readonly<Record<string, readonly string[]>> {
  const variables: Record<string, readonly string[]> = {};

  for (const [key, message] of [...flattenMessages(source)].sort(([a], [b]) =>
    a < b ? -1 : a > b ? 1 : 0,
  )) {
    const names = analyzeMessage(message).variables;

    if (names !== undefined && names.size > 0) {
      variables[key] = [...names].sort();
    }
  }

  return variables;
}

const GENERATED_HEADER = [
  '// Generated by Etyma. Do not edit.',
  '// Derived from a remote message catalog - see the Etyma Vite plugin (etymaRemoteContract).',
].join('\n');

/**
 * Renders a {@link https://www.npmjs.com/package/@etyma/core `defineMessageContract`} module
 * from a key list and, optionally, each message's variables.
 *
 * Byte-stable for a given input: no timestamp, no random id, no machine-specific path -
 * running this twice against the same catalog produces the same file, so committing the
 * output never causes churn the catalog itself did not cause. Without variables (or with
 * none to list) the module is exactly the keys-only one earlier versions generated.
 */
export function renderContractModule(
  keys: readonly string[],
  variables: Readonly<Record<string, readonly string[]>> = {},
): string {
  const sortedKeys = [...keys].sort();
  const variableKeys = Object.keys(variables).sort();
  const header =
    `${GENERATED_HEADER}\n` +
    `\n` +
    `import { defineMessageContract } from '@etyma/core';\n` +
    `\n`;

  if (variableKeys.length === 0) {
    const literal = sortedKeys.map(key => `  ${JSON.stringify(key)},`).join('\n');

    return `${header}export default defineMessageContract([\n${literal}\n] as const);\n`;
  }

  const keyLiteral = sortedKeys.map(key => `    ${JSON.stringify(key)},`).join('\n');
  const variableLiteral = variableKeys
    .map(key => {
      const names = [...(variables[key] ?? [])].sort().map(name => JSON.stringify(name));

      return `    ${JSON.stringify(key)}: [${names.join(', ')}],`;
    })
    .join('\n');

  return (
    `${header}export default defineMessageContract(\n` +
    `  [\n${keyLiteral}\n  ] as const,\n` +
    `  {\n${variableLiteral}\n  } as const,\n` +
    `);\n`
  );
}
