import { EtymaError, flattenMessages } from '@etyma/core';
import { describe, expect, it } from 'vitest';

import { extractContractKeys, renderContractModule } from './generate-contract.js';

describe('extractContractKeys', () => {
  it('sorts dotted keys regardless of the catalog authoring order', () => {
    const keys = extractContractKeys({ welcome: 'Hello', nav: { docs: 'Docs' } });

    expect(keys).toEqual(['nav.docs', 'welcome']);
  });

  it('matches the key set flattenMessages derives for the same catalog', () => {
    const catalog = {
      nav: { docs: 'Docs', components: 'Components' },
      footer: { rights: 'MIT licensed.' },
    };

    expect(extractContractKeys(catalog)).toEqual([...flattenMessages(catalog).keys()].sort());
  });

  it('walks arbitrarily deep', () => {
    expect(extractContractKeys({ a: { b: { c: { d: 'deep' } } } })).toEqual(['a.b.c.d']);
  });

  it('rejects a dotted key, the same as flattenMessages does', () => {
    expect(() => extractContractKeys({ 'nav.docs': 'Docs' })).toThrow(EtymaError);
    expect(() => extractContractKeys({ 'nav.docs': 'Docs' })).toThrow(/contains a "\."/);
  });

  it('rejects a non-string leaf', () => {
    expect(() => extractContractKeys({ count: 3 as unknown as string })).toThrow(
      /"count" is a number/,
    );
  });

  it('rejects a malformed catalog root', () => {
    expect(() => extractContractKeys(null as unknown as never)).toThrow(/root is null/);
  });

  it('keeps every exact index of an array, since the real catalog is at hand', () => {
    expect(extractContractKeys({ features: ['A', 'B'] })).toEqual(['features.0', 'features.1']);
  });

  it('sorts indexed keys the same way as every other key: as strings, not numbers', () => {
    // The contract's order is the existing deterministic string sort, not the array's order -
    // `items.10` before `items.2`. Traversal itself stays in array order (see core's tests).
    const items = Array.from({ length: 11 }, (_, index) => `item ${index}`);

    expect(extractContractKeys({ items }).slice(0, 4)).toEqual([
      'items.0',
      'items.1',
      'items.10',
      'items.2',
    ]);
  });

  it('rejects an empty array, the same as flattenMessages does', () => {
    expect(() => extractContractKeys({ features: [] })).toThrow(/"features" is an empty array/);
  });
});

describe('renderContractModule', () => {
  it('renders a deterministic, sorted defineMessageContract module', () => {
    expect(renderContractModule(['welcome', 'nav.docs'])).toBe(
      [
        '// Generated by Etyma from a source message catalog. Do not edit.',
        '// Regenerate it with `etyma contract` (local JSON) or etymaRemoteContract (remote catalog).',
        '',
        "import { defineMessageContract } from '@etyma/core';",
        '',
        'export default defineMessageContract([',
        '  "nav.docs",',
        '  "welcome",',
        '] as const);',
        '',
      ].join('\n'),
    );
  });

  it('produces byte-identical output for the same keys given in a different order', () => {
    expect(renderContractModule(['b', 'a'])).toBe(renderContractModule(['a', 'b']));
  });

  it('escapes a key containing a quote safely', () => {
    expect(renderContractModule(["it's"])).toContain(JSON.stringify("it's"));
  });

  it('contains no timestamp, random id or absolute path', () => {
    const output = renderContractModule(['nav.docs']);

    expect(output).not.toMatch(/\d{4}-\d{2}-\d{2}/);
    expect(output).not.toMatch(/\/(Users|home)\//);
  });
});
