import { EtymaError, flattenMessages, type MessageSource } from '@etyma/core';

import { analyzeMessage } from './message-analysis.js';

/**
 * Extracts a message catalog's key contract, deterministically sorted.
 *
 * Built on `@etyma/core`'s own `flattenMessages` rather than a second catalog walker: the
 * same validation a static `source` catalog gets - no dotted or duplicate keys, every leaf a
 * string or a non-empty array of strings - applies here too, and throws the same way, whether
 * the catalog is a local file or a remote one.
 *
 * Only the keys are kept. The message values themselves are never part of a generated
 * contract - the source catalog stays the one place translation content lives.
 */
export function extractContractKeys(source: MessageSource): readonly string[] {
  return [...flattenMessages(source).keys()].sort();
}

/** Options for {@link extractContractVariables}. */
export interface ExtractContractVariablesOptions {
  /**
   * Throw for a message that is not valid MessageFormat 2 syntax, naming every such key,
   * instead of leaving it out. Off by default: `etymaRemoteContract` leaves reporting to
   * `etymaRemoteValidation`; `etyma contract`, asked explicitly to describe one catalog, sets
   * it.
   */
  readonly strict?: boolean;
}

/**
 * Extracts each message's external MessageFormat 2 variables, for a contract that types
 * `t()`'s params as well as its keys.
 *
 * Read with the `messageformat` parser, through the same analysis `validateCatalogs` compares
 * variables with - never a regex. Only messages with at least one variable get an entry, and
 * both keys and names are sorted, so the result is deterministic. A message that is not valid
 * MessageFormat 2 syntax has no knowable variables: by default it gets no entry, and so keeps
 * untyped params, leaving the syntax error to validation; with `strict` it throws. A message
 * that parses but breaks a data-model rule (a missing fallback variant, say) still has exact
 * variables and gets its entry either way - `validateCatalog` reports those.
 *
 * Throws on a malformed catalog shape exactly as {@link extractContractKeys} does.
 */
export function extractContractVariables(
  source: MessageSource,
  options: ExtractContractVariablesOptions = {},
): Readonly<Record<string, readonly string[]>> {
  const variables: Record<string, readonly string[]> = {};
  const invalid: string[] = [];

  for (const [key, message] of [...flattenMessages(source)].sort(([a], [b]) =>
    a < b ? -1 : a > b ? 1 : 0,
  )) {
    const analysis = analyzeMessage(message);
    const names = analysis.variables;

    if (names === undefined) {
      invalid.push(`  ${key}: ${analysis.diagnostics[0]?.message ?? 'invalid syntax'}`);
    } else if (names.size > 0) {
      variables[key] = [...names].sort();
    }
  }

  if (options.strict === true && invalid.length > 0) {
    throw new EtymaError(
      `${invalid.length} source ${invalid.length === 1 ? 'message is' : 'messages are'} not ` +
        `valid MessageFormat 2, so ${invalid.length === 1 ? 'its' : 'their'} variables ` +
        `cannot be read:\n${invalid.join('\n')}`,
    );
  }

  return variables;
}

const GENERATED_HEADER = [
  '// Generated by Etyma from a source message catalog. Do not edit.',
  '// Regenerate it with `etyma contract` (local JSON) or etymaRemoteContract (remote catalog).',
].join('\n');

/**
 * Renders a {@link https://www.npmjs.com/package/@etyma/core `defineMessageContract`} module
 * from a key list and, optionally, each message's variables - the one artifact both
 * `defineI18n({ contract })` and `defineRemoteI18n` read. It imports only `@etyma/core`.
 *
 * Byte-stable for a given input: no timestamp, no random id, no machine-specific path -
 * running this twice against the same catalog produces the same file, so committing the
 * output never causes churn the catalog itself did not cause. Without variables (or with
 * none to list) the module is exactly the keys-only one earlier versions generated.
 */
export function renderContractModule(
  keys: readonly string[],
  variables: Readonly<Record<string, readonly string[]>> = {},
): string {
  const sortedKeys = [...keys].sort();
  const variableKeys = Object.keys(variables).sort();
  const header =
    `${GENERATED_HEADER}\n` +
    `\n` +
    `import { defineMessageContract } from '@etyma/core';\n` +
    `\n`;

  if (variableKeys.length === 0) {
    const literal = sortedKeys.map(key => `  ${JSON.stringify(key)},`).join('\n');

    return `${header}export default defineMessageContract([\n${literal}\n] as const);\n`;
  }

  const keyLiteral = sortedKeys.map(key => `    ${JSON.stringify(key)},`).join('\n');
  const variableLiteral = variableKeys
    .map(key => {
      const names = [...(variables[key] ?? [])].sort().map(name => JSON.stringify(name));

      return `    ${JSON.stringify(key)}: [${names.join(', ')}],`;
    })
    .join('\n');

  return (
    `${header}export default defineMessageContract(\n` +
    `  [\n${keyLiteral}\n  ] as const,\n` +
    `  {\n${variableLiteral}\n  } as const,\n` +
    `);\n`
  );
}
