import {
  type I18nDefinition,
  type LocaleTuple,
  validateLocales,
  validateSourceLocale,
} from './define-i18n.js';
import { EtymaError } from './errors.js';
import type { MessageFormatterOptions } from './format.js';
import { localeDirection, type Locale, type TextDirection } from './locale.js';
import type { MessageLoader } from './loader.js';
import type { MessageContract } from './messages.js';
import { createLocaleRouter } from './routing.js';
import { returnMessageKey, type MissingMessageHandler } from './translator.js';

export interface RemoteI18nOptions<TKey extends string, TLocales extends LocaleTuple> {
  /** Every locale the application publishes, as BCP 47 tags. */
  readonly locales: TLocales;

  /**
   * The locale every other locale falls back to.
   *
   * Unlike `defineI18n`, this locale is not special at load time - it is loaded through
   * {@link RemoteI18nOptions.loaders} exactly like every other locale. It stays special at
   * the type level and at the fallback level: {@link RemoteI18nOptions.contract} describes
   * its shape, and a page in any locale falls back to it for a key its own catalog lacks.
   */
  readonly sourceLocale: TLocales[number];

  /**
   * The compile-time key contract, decoupled from the runtime source catalog.
   *
   * Typically generated by `@etyma/tooling`'s Vite plugin from the remote source catalog's
   * shape - see `defineMessageContract`. This is where `t()`'s typed keys come from, since
   * there is no static source object here for `MessageKey` to read.
   */
  readonly contract: MessageContract<TKey>;

  /**
   * How to fetch every locale's catalog, including the source locale.
   *
   * Required for all of them: unlike `defineI18n`, no locale here is loaded synchronously as
   * part of the initial bundle, so none can be skipped.
   */
  readonly loaders: Readonly<Record<TLocales[number], MessageLoader>>;

  /**
   * Override the detected text direction of a locale.
   *
   * Only needed where the runtime's own answer is missing and Etyma's fallback table is
   * wrong for the language in question.
   */
  readonly textDirection?: Readonly<Partial<Record<TLocales[number], TextDirection>>>;

  /** What renders in place of a message that exists in no catalog. Defaults to the key. */
  readonly onMissingMessage?: MissingMessageHandler;

  /** MessageFormat 2 behaviour: bidi isolation, custom functions, issue reporting. */
  readonly formatting?: MessageFormatterOptions;

  /**
   * Distinguishes this definition's SSR transfer payload from another's.
   *
   * Only matters in the rare application that provides two catalogs side by side.
   */
  readonly id?: string;
}

/**
 * Validates a remote i18n configuration and freezes it into an {@link I18nDefinition}.
 *
 * The remote counterpart to `defineI18n`, for an application whose translation content -
 * including the source locale's - lives behind a loader rather than a static import. The
 * compile-time key contract and the runtime source catalog are deliberately decoupled here:
 * `contract` supplies `TKey`, and `loaders` supplies every locale's messages, asynchronously.
 *
 * Every locale needs a loader, including the source locale - the inverse of `defineI18n`,
 * where the source locale must not have one. A definition from here has no `sourceCatalog`
 * until the source locale's loader has actually run; `createCatalogRegistry` and
 * `createTranslator` both treat that as a normal, expected state, not a special case.
 */
export function defineRemoteI18n<const TKey extends string, const TLocales extends LocaleTuple>(
  options: RemoteI18nOptions<TKey, TLocales>,
): I18nDefinition<TKey> {
  const locales: readonly Locale[] = [...options.locales];

  validateLocales('defineRemoteI18n', locales);

  const { sourceLocale } = options;

  validateSourceLocale('defineRemoteI18n', locales, sourceLocale);

  const seen = new Set(locales);
  const configuredLoaders = options.loaders as Readonly<Partial<Record<Locale, MessageLoader>>>;

  for (const locale of Object.keys(configuredLoaders)) {
    if (!seen.has(locale)) {
      throw new EtymaError(
        `defineRemoteI18n: loader configured for unknown locale "${locale}". ` +
          `Configured locales: [${locales.join(', ')}].`,
      );
    }
  }

  const loaders = new Map<Locale, MessageLoader>();

  for (const locale of locales) {
    const loader = configuredLoaders[locale];

    if (loader === undefined) {
      throw new EtymaError(
        `defineRemoteI18n: locale "${locale}" has no loader. Every locale, including the ` +
          'source locale, is loaded remotely and needs one, for example ' +
          `\`loaders: { ${locale}: createHttpMessageLoader('.../${locale}.json') }\`.`,
      );
    }

    if (typeof loader !== 'function') {
      throw new EtymaError(
        `defineRemoteI18n: loader for locale "${locale}" is a ${typeof loader}; expected a function.`,
      );
    }

    loaders.set(locale, loader);
  }

  const directions = new Map<Locale, TextDirection>(
    Object.entries(options.textDirection ?? {}).filter(
      (entry): entry is [Locale, TextDirection] => entry[1] !== undefined,
    ),
  );

  const definition: I18nDefinition<TKey> = {
    id: options.id ?? 'etyma',
    locales,
    sourceLocale,
    keys: options.contract.keys,
    sourceCatalog: undefined,
    router: createLocaleRouter({ locales, sourceLocale }),
    formatting: options.formatting ?? {},
    onMissingMessage: options.onMissingMessage ?? returnMessageKey,
    loaderFor: (locale: Locale) => loaders.get(locale),
    directionOf: (locale: Locale) => directions.get(locale) ?? localeDirection(locale),
  };

  return Object.freeze(definition);
}
