// Generated by Etyma from a source message catalog. Do not edit.
// Regenerate it with `etyma contract` (local JSON) or etymaRemoteContract (remote catalog).

import { defineMessageContract } from '@etyma/core';

export default defineMessageContract({
  keys: [
    "nav.docs",
    "remote.active",
    "remote.lede",
    "remote.title",
  ],
  variables: {
    "remote.active": ["locale"],
  },
});
