// Generated by Etyma. Do not edit.
// Derived from a remote message catalog - see the Etyma Vite plugin (etymaRemoteContract).

import { defineMessageContract } from '@etyma/core';

export default defineMessageContract([
  "nav.docs",
  "remote.active",
  "remote.lede",
  "remote.title",
] as const);
