import { defineRemoteI18n, type MessageLoader } from '@etyma/core';

import contract from './contract.generated.js';
import { remoteCatalogs, type RemoteLocale } from './catalogs.js';

/**
 * Simulates an asynchronous remote load without any real network I/O.
 *
 * A real application points a locale at `createHttpMessageLoader(url)` instead. This fixture
 * needs to run offline and deterministically in CI, the same requirement every other test in
 * this milestone has, so it wraps the same fixture data in a genuinely asynchronous
 * `Promise` instead of a real `fetch` - Etyma's registry, hydration and fallback logic treat
 * the two identically, since none of it inspects what is inside a loader.
 */
function delayedLoader(locale: RemoteLocale): MessageLoader {
  return () =>
    new Promise(resolve => {
      setTimeout(() => {
        resolve(remoteCatalogs[locale]);
      }, 10);
    });
}

/**
 * The dogfood case that motivated this milestone: no static source catalog at all. Every
 * locale, including the source (`en`), is loaded remotely. `contract` - generated by
 * `etymaRemoteContract` in `vite.config.ts` from `fixture-source.ts`'s shape - is what makes
 * `t('remote.title')` a compile error for a key `remoteCatalogs` doesn't define, exactly as
 * typed as the static `i18n` next to it.
 */
export const remoteI18n = defineRemoteI18n({
  locales: ['en', 'es', 'uk'],
  sourceLocale: 'en',
  contract,
  loaders: {
    en: delayedLoader('en'),
    es: delayedLoader('es'),
    uk: delayedLoader('uk'),
  },
});

/** Every message key the generated contract defines. */
export type RemoteMessageId = (typeof remoteI18n.keys)[number];
